server:
  port: 8080

adminPath: admin
apiPath: openApi

swallow:
  muti-datasource:
    open: true
  spring-session-open: false
  kaptchaOpen: false                #是否开启后台登录验证码
  swagger-open: true

spring:
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
  devtools:
    add-properties: false
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view/

  profiles:
    active: local
#  freemarker:
#    request-context-attribute: req
#    suffix: .html
#    content-type: text/html
#    enabled: true
#    cache: false
#    template-loader-path: classpath:/WEB-INF/view
#    charset: UTF-8
#    settings:
#      number_format: '0.##'

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

mybatis:
  type-aliases-package: cn.swallow.platform.modular.**.entity
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info      #日志打印级别
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://120.79.225.48:3306/spring_boot_demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: spring_boot_demo
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---

spring:
  profiles: local
  master-datasource:
    url: jdbc:mysql://localhost:3306/swallow_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_test
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  slave-datasource:
    url: jdbc:mysql://localhost:3306/swallow_test2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_test2
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---